/**
 * Asserts the TypeScript engine reproduces the Python engine exactly.
 *
 * Fixtures are generated by `python3 python/gen_fixtures.py`. If you change
 * the algorithm in one language, regenerate and this test tells you whether
 * the other language followed.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import { evaluate } from "../src/lib/signal.ts";
import { summarize } from "../src/lib/stats.ts";
import type { Point } from "../src/lib/stats.ts";

interface Fixture {
  name: string;
  series: Point[];
  priceLevel: string | null;
  typicalLow: number | null;
  typicalHigh: number | null;
  departureDate: string;
  asOf: string;
  expected: {
    action: string;
    score: number;
    confidence: string;
    daysToDeparture: number;
    targetPrice: number | null;
    nComponents: number;
    componentNames: string[];
    summary: {
      nDays: number;
      current: number | null;
      minimum: number | null;
      maximum: number | null;
      mean: number | null;
      pctRank: number | null;
      slope14d: number | null;
      week: { currentAvg: number | null; previousAvg: number | null; deltaPct: number | null; direction: string };
      month: { currentAvg: number | null; previousAvg: number | null; deltaPct: number | null; direction: string };
    };
  };
}

const fixtures: Fixture[] = JSON.parse(
  readFileSync(new URL("./fixtures/parity.json", import.meta.url), "utf8"),
);

// Python snake_case component names -> TypeScript camelCase.
const NAME_MAP: Record<string, string> = {
  google_price_level: "googlePriceLevel",
  typical_range_position: "typicalRangePosition",
  history_percentile: "historyPercentile",
  momentum_7d: "momentum7d",
  momentum_30d: "momentum30d",
  deadline_pressure: "deadlinePressure",
};

/** Floating-point comparison tolerant of last-digit rounding differences. */
function closeTo(actual: number | null, expected: number | null, eps = 0.05, label = "") {
  if (expected === null || actual === null) {
    assert.equal(actual, expected, `${label}: one side is null`);
    return;
  }
  assert.ok(
    Math.abs(actual - expected) <= eps,
    `${label}: expected ${expected}, got ${actual} (diff ${Math.abs(actual - expected)})`,
  );
}

assert.ok(fixtures.length >= 10, "expected at least 10 parity fixtures");

for (const fx of fixtures) {
  test(`parity: ${fx.name}`, () => {
    const summary = summarize(fx.series);
    const exp = fx.expected.summary;

    // --- stats.ts parity ---
    assert.equal(summary.nDays, exp.nDays, "nDays");
    closeTo(summary.current, exp.current, 0.01, "current");
    closeTo(summary.minimum, exp.minimum, 0.01, "minimum");
    closeTo(summary.maximum, exp.maximum, 0.01, "maximum");
    closeTo(summary.mean, exp.mean, 0.01, "mean");
    closeTo(summary.pctRank, exp.pctRank, 1e-9, "pctRank");
    closeTo(summary.slope14d, exp.slope14d, 0.02, "slope14d");

    closeTo(summary.week.currentAvg, exp.week.currentAvg, 0.01, "week.currentAvg");
    closeTo(summary.week.previousAvg, exp.week.previousAvg, 0.01, "week.previousAvg");
    closeTo(summary.week.deltaPct, exp.week.deltaPct, 0.01, "week.deltaPct");
    assert.equal(summary.week.direction, exp.week.direction, "week.direction");

    closeTo(summary.month.currentAvg, exp.month.currentAvg, 0.01, "month.currentAvg");
    closeTo(summary.month.previousAvg, exp.month.previousAvg, 0.01, "month.previousAvg");
    closeTo(summary.month.deltaPct, exp.month.deltaPct, 0.01, "month.deltaPct");
    assert.equal(summary.month.direction, exp.month.direction, "month.direction");

    // --- signal.ts parity ---
    const verdict = evaluate({
      currentPrice: summary.current,
      summary,
      priceLevel: fx.priceLevel,
      typicalLow: fx.typicalLow,
      typicalHigh: fx.typicalHigh,
      departureDate: fx.departureDate,
      asOf: fx.asOf,
    });

    assert.equal(verdict.action, fx.expected.action, "action");
    closeTo(verdict.score, fx.expected.score, 0.05, "score");
    assert.equal(verdict.confidence, fx.expected.confidence, "confidence");
    assert.equal(verdict.daysToDeparture, fx.expected.daysToDeparture, "daysToDeparture");
    closeTo(verdict.targetPrice, fx.expected.targetPrice, 0.01, "targetPrice");

    assert.equal(verdict.components.length, fx.expected.nComponents, "component count");
    assert.deepEqual(
      verdict.components.map((c) => c.name).sort(),
      fx.expected.componentNames.map((n) => NAME_MAP[n] ?? n).sort(),
      "component names",
    );
  });
}
